### ISSUE TITLE
Problem with CardGameBuilder

### ISSUE THREAD

**Issue by Sajmonpcgamer** [psuba1100/CardGameBuilder#1]
Hello @psuba1100 , i tried to download your "CardGameBuilder", but when i open "index.html" the game will just bug off and dont work as intended. Is this just a beta or is it a problem i have or i just dont understand how it works.

- Thanks, Sajmo
![unknown](https://user-images.githubusercontent.com/80468592/164750724-49415f46-d90f-45a2-b7aa-b080dd6bbbf3.png)
n

**Comment by psuba1100** [comment]
this api is in progress. What you see is debugger version without any features. please wait until first official release :)
